# Generated by Django 5.0.6 on 2024-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_new_user_options_alter_new_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='username',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
