# Generated by Django 5.0.6 on 2024-06-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_new_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
