# Generated by Django 5.0.6 on 2024-06-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_new_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user',
            name='image',
        ),
    ]
