# Generated by Django 5.0.6 on 2024-06-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_new_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
